/* Copyright (c) 2011 Cengage Learning Inc. */
/* cim v0048 */
(function(d){function j(a){this.loadedDef=d.Deferred();this.settings=a;this.launchListeners=[];this.stateChangeListeners=[];if(!a.containerElementId||typeof a.containerElementId!="string")throw Error("Null value for 'containerElementId' setting.  Value must be a string.");if(a.covalentHost&&typeof a.covalentHost!="string")throw Error("Unrecognized value for 'covalentHost' setting.  Value must be a string.");if(a.error&&typeof a.error!="function")throw Error("Unrecognized value for 'error' setting.  Value must be a function.");
if(a=a.launchListeners){d.isArray(a)||(a=[a]);d.each(a,function(b,c){if(typeof c!="function")throw Error("launch listener must be a function.");});this.launchListeners=[].concat(a)}this.itemService=new CovalentItemService(this.settings.covalentHost,this.settings.covalentHostTimeout);this._launch()}d.extend(j.prototype,{isSecure:function(){return this.settings.secureParams!=null},getContainerElement:function(){return document.getElementById(this.settings.containerElementId)},getLoadingDeferred:function(){return this.loadedDef},
addLaunchChangeListener:function(a){this.launchListeners.push(a)},addItemStateChangeListener:function(a){this.stateChangeListeners.push(a)},getItemService:function(){return this.itemService},_launch:function(){var a={secureParams:this.settings.secureParams,answerData:this.settings.answerData,rendererParams:this.settings.rendererParams,messageParams:this.settings.messageParams,redraw:true,drawMode:this.settings.drawMode};this.isSecure()||(a={answerData:this.settings.answerData,itemUri:this.settings.itemUri,
rendererId:this.settings.rendererId,rendererDefinitionUrl:this.settings.rendererDefinitionUrl,covalentItemRenderingOptions:this.settings.covalentItemRenderingOptions});return this._requestItem(a)},requestState:function(a,b,c,e){return this._requestItem(this.buildStateParams(b,c,e),a)},buildStateParams:function(a,b,c){if(b&&this.reRender(false,true))b=false;var e=this._getItem().getSubmitString();if(c)e+="&submitMode="+c;a={answerData:e,secureParams:this.settings.secureParams,messageParams:a,drawMode:b?
"diff":"full",redraw:b};this.isSecure()||(a={answerData:e,itemUri:this.settings.itemUri,rendererId:this.settings.rendererId,rendererDefinitionUrl:this.settings.rendererDefinitionUrl,covalentItemRenderingOptions:this.settings.covalentItemRenderingOptions});return a},_requestItem:function(a,b){var c=d.proxy(function(e){this._onRequestItemFinished(e,a,b);this.loadedDef.resolve()},this);return this.isSecure()?this.itemService.secureGetItemScript(a,c,this.settings.error).pipe(d.proxy(this._processRequestItemState,
this)):this.itemService.getItemScript(a,c,this.settings.error).pipe(d.proxy(this._processRequestItemState,this))},_onRequestItemFinished:function(a,b,c){if(typeof a.nextSecureParams!="undefined")this.settings.secureParams=a.nextSecureParams;if(a.renderFullItem)this._renderFull(a);else a.diffJavascript&&this._renderDiff(a);c&&c(this._processRequestItemState(a))},_processRequestItemState:function(a){return this.isSecure()?a.secureState:a.state},_renderFull:function(a){this.destroy();this.itemUid=a.itemUid;
var b=(a.rendererHtml+a.itemHtml).replace(/--\>\s*<\/script>/g,"//--\><\/script>"),c=d.ajaxSetup().cache;d.ajaxSetup({cache:true});d(this.getContainerElement()).html(b);if(c===undefined)delete d.ajaxSetup().cache;else d.ajaxSetup({cache:c});if(typeof window[a.rendererClass]=="undefined")throw"Unable to locate renderer class: "+a.rendererClass;a=new window[a.rendererClass];typeof this.settings.itemRendererOverride=="object"&&this._overrideRenderer(a,this.settings.itemRendererOverride);this._getItem().addItemLoadedListener(d.proxy(this._callLaunchListeners,
this));this._getItem().addItemLoadedListener(function(){d(window).trigger("stepLoaded")});this._getItemManager().pageLoaded(a);this._getItem().addStateChangeListener(d.proxy(this._callStateChangeListeners,this))},_overrideRenderer:function(a,b){var c=d.extend({},a),e=d.extend({},a,b,{"super":c});d.each(b,function(f,p){var l=typeof a[f],i=typeof b[f];if(l!="undefined"&&l!=i)throw"itemRendererOverride type of '"+f+"' field ("+i+") does not match original type in renderer ("+l+")";if(i=="function")p=
function(){return b[f].apply(e,arguments)};a[f]=p})},_renderDiff:function(a){if(this.isItemAvailable()){var b=this._getItem();try{var c=eval(a.diffJavascript)}catch(e){throw"Error evaluating diff JS: "+e;}c(b)}},_callStateChangeListeners:function(a){d.each(this.stateChangeListeners,function(b,c){c(a)})},_callLaunchListeners:function(){d.each(this.launchListeners,function(a,b){b()})},_getItemManager:function(){if(typeof CovalentItemManager=="undefined")throw"ItemHandle: CovalentItemManager is not yet defined.";
return CovalentItemManager.getInstance()},_getItem:function(){return this._getItemManager().findItem(this.itemUid)},isItemAvailable:function(){var a=null;try{a=this._getItem()}catch(b){return false}return a&&typeof a=="object"},isModified:function(){var a=this._getItem();return a&&a.isModified()},markUnmodified:function(){this._getItem().markUnmodified()},destroy:function(){try{var a=this._getItem();a.remove();a.clearRejoinders();d(this.getContainerElement()).empty()}catch(b){}},reRender:function(a,
b,c){return this._getItem().renderItem(c,a,b)},clearItem:function(){try{this._getItem().clearItem()}catch(a){}},clearRejoinders:function(){this._getItem().clearRejoinders()},clearInfoAndHint:function(){this._getItem().clearInfoAndHint()},getAdditionalInfos:function(){return this._getItem().getAdditionalInfos()},getHints:function(){return this._getItem().getHints()}});window.com_cengage_covalent_widgets_CovalentItem=j})(jQuery);
function CovalentItemService(d,j){if(!d){d=CovalentUtils.resolveCovalentHost("cim_min.js");if(!d)throw Error("Unable to resolve covalent host.");}var a=window.location.protocol.indexOf("https")===0;this.restService=new CovalentXDClient(d,"/ilrn/service/covalentItem",a,j)}
CovalentItemService.prototype._prepareLaunchParams=function(d){d.restReceiverUrl="restReceiverUrl parameter is required but no longer used.";if(typeof d.covalentItemRenderingOptions=="object")d.covalentItemRenderingOptions=JSON.stringify(d.covalentItemRenderingOptions,null,null)};CovalentItemService.prototype.getItemScript=function(d,j,a){this._prepareLaunchParams(d);return this.restService.postRequestJSON("",d,j,a)};
CovalentItemService.prototype.secureGetItemScript=function(d,j,a){this._prepareLaunchParams(d);return this.restService.postRequestJSON("/secure",d,j,a)};function CovalentUtils(){}CovalentUtils.resolveCovalentHost=function(d){if(d=jQuery('script[src$="'+d+'"]'))if((d=d.attr("src").match(/^\w+:\/\/([^\/]+)/))&&d.length>1)return d[1];return null};
var CovalentXDClient=function(d,j){function a(b,c,e,f){var p=b.indexOf("https")===0,l=window.location.protocol.indexOf("https")===0;this.host=b.replace(/^https?:\/\//,"").replace(/\/$/,"");this.basePath=c.replace(/^\/?/,"/").replace(/\/?$/,"")||"";this.useSecureProtocol=e||p||l;if(f){f=Number(j.trim(f));if(f<=5E3)throw Error("You cannot set the timeout to a value that is less than 5000 milliseconds.");}else f=3E4;this.timeout=f}j.extend(a.prototype,{getString:function(b,c,e,f){return this.get(b,c,
"text",e,f)},getJSON:function(b,c,e,f){return this.get(b,c,"json",e,f)},getXML:function(b,c,e,f){return this.get(b,c,"xml",e,f)},postRequestString:function(b,c,e,f){return this.post(b,c,"text",e,f)},postRequestJSON:function(b,c,e,f){return this.post(b,c,"json",e,f)},postRequestXML:function(b,c,e,f){return this.post(b,c,"xml",e,f)},get:function(b,c,e,f,p){return this._send("GET",b,c,e,f,p)},post:function(b,c,e,f,p){return this._send("POST",b,c,e,f,p)},_send:function(b,c,e,f,p,l){if(typeof e=="object"){e=
j.extend(true,{},e);this._formatParams(e)}var i=this.useSecureProtocol?"https":"http",n=j.ajax({url:i+"://"+this.host+this.basePath+c.replace(/^\/?/,"/"),type:b,cache:false,crossDomain:window.location.host!=this.host||window.location.protocol!=i+":",data:e,dataType:f,success:function(g){typeof p=="function"&&setTimeout(function(){p(g)},1)},error:function(g){typeof l=="function"&&setTimeout(function(){var k={status:g.status||"",statusText:g.statusText||"",message:g.responseText||"",type:"unknown",
code:"unknown"};try{var m=j.parseJSON(g.responseText);m&&j.extend(k,m)}catch(r){}l(k)},1)},complete:function(g,k){if(k=="timeout")n.responseText="Timeout while waiting for response from server"},timeout:this.timeout});return n},_formatParams:function(b){for(var c in b){if(typeof b[c]=="function")throw Error("Invalid value of "+c+" parameter: function values are not supported by this framework.");if(typeof b[c]=="boolean")b[c]=b[c]?"true":"false";b[c]==null&&delete b[c]}}});return a}(jQuery,jQuery);
(function(d){if(!(d.support.cors||typeof XDomainRequest=="undefined")){if(typeof d.ajaxTransport=="undefined")throw Error("This library requires jQuery 1.5.1 or later.");d.ajaxTransport(function(j){if(!(!j.crossDomain||j.dataType=="jsonp")){var a;return{send:function(b,c){a=new XDomainRequest;a.onload=function(){var e={text:a.responseText};if(a.contentType.match(/\/xml/)){var f=new ActiveXObject("Microsoft.XMLDOM");f.async=false;f.loadXML(a.responseText);e.xml=f}c(200,"success",e)};a.onerror=a.ontimeout=
function(){c(400,"failed",{text:a.responseText})};a.onprogress=function(){};a.open(j.type,j.url);"POST"==j.type?a.send(j.data):a.send()},abort:function(){a&&a.abort()}}}})}})(jQuery);var JSON;JSON||(JSON={});
(function(){function d(i){return i<10?"0"+i:i}function j(i){c.lastIndex=0;return c.test(i)?'"'+i.replace(c,function(n){var g=p[n];return typeof g==="string"?g:"\\u"+("0000"+n.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+i+'"'}function a(i,n){var g,k,m,r,q=e,o,h=n[i];if(h&&typeof h==="object"&&typeof h.toJSON==="function")h=h.toJSON(i);if(typeof l==="function")h=l.call(n,i,h);switch(typeof h){case "string":return j(h);case "number":return isFinite(h)?String(h):"null";case "boolean":case "null":return String(h);
case "object":if(!h)return"null";e+=f;o=[];if(Object.prototype.toString.apply(h)==="[object Array]"){r=h.length;for(g=0;g<r;g+=1)o[g]=a(g,h)||"null";m=o.length===0?"[]":e?"[\n"+e+o.join(",\n"+e)+"\n"+q+"]":"["+o.join(",")+"]";e=q;return m}if(l&&typeof l==="object"){r=l.length;for(g=0;g<r;g+=1)if(typeof l[g]==="string"){k=l[g];if(m=a(k,h))o.push(j(k)+(e?": ":":")+m)}}else for(k in h)if(Object.prototype.hasOwnProperty.call(h,k))if(m=a(k,h))o.push(j(k)+(e?": ":":")+m);m=o.length===0?"{}":e?"{\n"+e+o.join(",\n"+
e)+"\n"+q+"}":"{"+o.join(",")+"}";e=q;return m}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+d(this.getUTCMonth()+1)+"-"+d(this.getUTCDate())+"T"+d(this.getUTCHours())+":"+d(this.getUTCMinutes())+":"+d(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var b=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
c=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e,f,p={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},l;if(typeof JSON.stringify!=="function")JSON.stringify=function(i,n,g){var k;f=e="";if(typeof g==="number")for(k=0;k<g;k+=1)f+=" ";else if(typeof g==="string")f=g;if((l=n)&&typeof n!=="function"&&(typeof n!=="object"||typeof n.length!=="number"))throw Error("JSON.stringify");return a("",
{"":i})};if(typeof JSON.parse!=="function")JSON.parse=function(i,n){function g(m,r){var q,o,h=m[r];if(h&&typeof h==="object")for(q in h)if(Object.prototype.hasOwnProperty.call(h,q)){o=g(h,q);if(o!==undefined)h[q]=o;else delete h[q]}return n.call(m,r,h)}var k;i=String(i);b.lastIndex=0;if(b.test(i))i=i.replace(b,function(m){return"\\u"+("0000"+m.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(i.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){k=eval("("+i+")");return typeof n==="function"?g({"":k},""):k}throw new SyntaxError("JSON.parse");}})();