<!-- R Commander Markdown Template -->

Replace with Main Title
=======================

### Your Name

### `r as.character(Sys.Date())`

```{r echo=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE, out.width=750, fig.height=8, fig.width=8)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```


```{r echo=FALSE}
# include this code chunk as-is to enable 3D graphs
library(rgl)
knitr::knit_hooks$set(webgl = hook_webgl)
```


```{r}
UnivBank <- 
  read.table("C:/Users/jdine/Desktop/SYracuse/Business Analytics/Homeworks/Hw4/scm651_homework_4_universal_bank.csv",
   header=TRUE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
```

```{r}
names(UnivBank)
```


```{r}
scatterplot(PersonalLoan~Income, reg.line=FALSE, smooth=FALSE, spread=FALSE,
   boxplots=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), data=UnivBank)
```

```{r}
GLM.1 <- glm(PersonalLoan ~ CCAvg + CDAccount + CreditCard + Education + 
  Family + Income + Online + SecuritiesAccount, family=binomial(logit), 
  data=UnivBank)
summary(GLM.1)
exp(coef(GLM.1))  # Exponentiated coefficients ("odds ratios")
```

```{r}
scatterplot(PersonalLoan~Income, reg.line=FALSE, smooth=FALSE, spread=FALSE, 
  boxplots=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), data=UnivBank)
```

